/*******************************************************************/                                     
/* SYSVALPRG - display systems value                               */                            
/* coded by: Prince Dineshkumar Jodhani                            */
/* signature: Prince Dineshkumar Jodhani                           */
/*******************************************************************/

DSPLIBL
EDTLIBL
DSPLIBL
DSPSYSVAL QSYSLIBL
DSPSYSVAL QUSRLIBL
DSPSYSVAL QMODEL  